name: Delete Old Artifacts

on:
  workflow_dispatch: 

jobs:
  delete_artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete old artifacts
        uses: actions/delete-artifact@v2
        with:
          name: php-app # Name of the artifact to delete (optional, if not provided all artifacts will be deleted)
          retention-days: 1 # Optional, specify the number of days of artifacts to keep (older artifacts will be deleted)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
